plugins {
	id 'java'
	id 'org.springframework.boot' version '4.1.0'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter'

	// Spring Data JPA
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	// Lombok
	implementation 'org.projectlombok:lombok'
	// Validation
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'

	// 스프링 서버를 실행 중인 상태에서 코드 수정 시 실시간 반영이 되게 해주는 의존성
	// 서버를 킨 상태에서 코드 수정 시 서버를 재시작 할 필요가 없습니다.
	developmentOnly 'org.springframework.boot:spring-boot-devtools'

	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}
